### ISSUE TITLE
Switch from Komada to Klasa

### ISSUE THREAD

**Issue by cfanoulis** [Rexogamer/klepton#5]
Hello there :wave: 

This is just a friendly reminder that the framework you're using is deprecated! The newest revision of komada is called Klasa, and has many more features and is much more stable than komada

**Comment by Rexogamer** [comment]
I’m up for this, but the NPM listing for Klasa was last updated 4 years ago.

**Comment by Rexogamer** [comment]
Also getting @CelestialCrafter’s attention

**Comment by cfanoulis** [comment]
Klasa is currently waiting for discordjs/discord.js to release v12, but you can install the `settings` branch (which is the most stable of them all) from github

**Comment by Rexogamer** [comment]
Indeed; however, what about the package.json?

**Comment by cfanoulis** [comment]
Well, you just install it thru npm/yarn and that takes care of the package?

**Comment by Rexogamer** [comment]
We’re dropping both.
